networks:
  maritime-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local

services:
  postgres:
    image: postgres:15-alpine
    container_name: maritime-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: maritime_logistics
      POSTGRES_USER: maritime_admin
      POSTGRES_PASSWORD: secure_password_2025
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      -